### PR TITLE
docker: add support for arm64, ppc64le, s390x, i386, armv7, armv6

### PR DESCRIPTION
**Pull request by sgsunder**

### CODE REVIEW

**Comment by noirscape** [comment]
any progress on this?

**Comment by sgsunder** [comment]
@noirscape As far as I can tell, the current master branch (From at least commit db0c33bb14748523545373672272739507c4f3c1 onwards) should be able build and run on non-x86 systems.

This PR was trying to enable multi-arch support for Docker Hub, which I still have no idea how to do.

So if you want to run on non-x86 systems you can, you just have to build the images yourselves instead of pulling from Docker Hub

**Comment by noirscape** [comment]
Alright, awesome. I'll do just that then.

**Comment by sgsunder** [comment]
Lol, less then a week after I close this I finally get a response: https://github.com/docker/buildx/issues/243

**Comment by sgsunder** [comment]
@noirscape ARM images are now available on Docker Hub! We're building them through GH Actions now.

**Comment by noirscape** [comment]
o7 thanks!

**Pull request closed without merging**
