### PR TITLE
Implement #204

### PR DESCRIPTION
**Pull request by raku-cat**
Shows source in posts, allows setting the source as well. Might need input sanitizing.

### CODE REVIEW

**Comment by rr-** [comment]
I'd like to avoid that text-ellipsis, if possible.

**Comment by sgsunder** [comment]
Maybe instead of

> Source: [http://example.com/image?id=foobar](http://example.com/image?id=foobar)

we can just show the domain name

> Source: [example.com](http://example.com/image?id=foobar)

and also we can hide the field entirely instead of showing

> Source: None!

**Comment by rr-** [comment]
Domain name, possibly with `/…`, with a tooltip and a working link. I like that.

**Comment by raku-cat** [comment]
> and also we can hide the field entirely instead of showing
> 
> > Source: None!

My reasoning for doing this was so the page looks consistent, same reason for truncating the URL, so there's not some long URL that makes the page extremely long.

**Comment by rr-** [comment]
Implemented by #223

**Pull request closed without merging**
