### PR TITLE
Fixed dependency name

### PR DESCRIPTION
**Pull request by kotcrab**
`postgres` package does not exist.

### CODE REVIEW

**Comment by kotcrab** [comment]
You also need to change `git clone https://github.com/rr-/szurubooru2 szuru` to `git clone https://github.com/rr-/szurubooru.git szuru` and `alembic update head` to `alembic upgrade head`. Sorry for not including it in the PR, didn't get that far yesterday.

**Comment by rr-** [comment]
Wait, why does it need `.git` suffix? Fixing `alembic` in a sec

**Comment by rr-** [comment]
Done in f1108a878b983388799607bb2918296c5d1e3fc9

**Comment by kotcrab** [comment]
Oh, `.git` suffix is probably not important. Change from `szurubooru2` to `szurubooru` was needed otherwise it asks for GitHub login details.

**Comment by kotcrab** [comment]
One more thing `./server/host-waitress` from root doesn't work. Looks like server assumes it is run from `server` and looks for `config.yaml.dist` in parent directory. So you actually need to run `./host-waitress` from `server` dir to start it.
```
(python_modules) [root@archlinux szuru]# ./server/host-waitress
Traceback (most recent call last):
  File "./server/host-waitress", line 13, in <module>
    from szurubooru.app import create_app
  File "/root/szuru/server/szurubooru/app.py", line 7, in <module>
    from szurubooru import api, config, errors, middleware
  File "/root/szuru/server/szurubooru/api/__init__.py", line 3, in <module>
    from szurubooru.api.password_reset_api import PasswordResetApi
  File "/root/szuru/server/szurubooru/api/password_reset_api.py", line 1, in <module>
    from szurubooru import config, errors
  File "/root/szuru/server/szurubooru/config.py", line 23, in <module>
    config = read_config() # pylint: disable=invalid-name
  File "/root/szuru/server/szurubooru/config.py", line 16, in read_config
    with open('../config.yaml.dist') as handle:
FileNotFoundError: [Errno 2] No such file or directory: '../config.yaml.dist'
(python_modules) [root@archlinux szuru]# cd server
(python_modules) [root@archlinux server]# ./server/host-waitress
-bash: ./server/host-waitress: No such file or directory
(python_modules) [root@archlinux server]# ./host-waitress
serving on http://0.0.0.0:6666
```

**Comment by rr-** [comment]
Yep, I only wanted to locate the script rather than showing how to run it. I guess it's a little misworded, I'll add a note about CWD

**Pull request merged**
