### PR TITLE
server: Fix snapshots and unit tests related to post flags

### PR DESCRIPTION
**Pull request by Hunternif**
TODO: scratch this and change flags to be an array.

Test still failing: `test_get_user_tokens`

### CODE REVIEW

**Comment by Hunternif** [comment]
But what about https://github.com/rr-/szurubooru/commit/3879c2ec20b1fa09408bbe7ba3bb93a35fab5796

**Comment by rr-** [comment]
This wasn't right, either.

**Comment by Hunternif** [comment]
Stored as a string in the database, but as an array in the application? Or do you think flags should be a table?

**Comment by Hunternif** [comment]
Don't "fix" these tests, should fix the implementation instead.

**Pull request closed without merging**
