### PR TITLE
Add .travis.yml

### PR DESCRIPTION
**Pull request by nothink**

### CODE REVIEW

**Comment by rr-** [comment]
Wouldn't it be better off to wait for #169 ?

**Comment by nothink** [comment]
Umm... it's certainly right. Please pend it.

**Comment by rr-** [comment]
Docker support has landed

**Comment by nothink** [comment]
OK.
This .travis.yml is based on 2.2 tag.
First of all, is it necessary to match with the current HEAD?

**Comment by rr-** [comment]
Yes, that's encouraged.

**Comment by nothink** [comment]
Umm... Pycodestyle is throwing up some errors, and test_image_hash.py failed.

**Comment by rr-** [comment]
Fixed failing test (regression caused by `HEAD^`).
`pycodestyle` raises known flags:

- `szurubooru/search/configs/post_search_config.py:72:35: E711 comparison to None should be 'if cond is None:'`
  "Fixing" this causes sqlalchemy to fail to produce proper query since it only overloads `__eq__` and not `is`.
- `szurubooru/migrations/env.py:12:1: E402 module level import not at top of file`
  `szurubooru/migrations/env.py:13:1: E402 module level import not at top of file`
  I don't see a clear way to refactor the code that doesn't make it obscure.

**Comment by nothink** [comment]
OK. Should I suppress messages E711, E402, and so on?

**Comment by rr-** [comment]
For time being I'd rather disable `pycodestyle` from the CI build.
For example we also use `pylint` but it too raises some flags that aren't suppressed.

**Comment by nothink** [comment]
All right. Server-side py.test was all passed.

**Comment by nothink** [comment]
Current tests:
 - Backend test for on-premise (3.6/3.7)
 - Check of docker-compose.yml
 - Check of building frontend

Need more?

**Pull request closed without merging**
