### PR TITLE
Feature Improvement : Automatic child relations

### PR DESCRIPTION
**Pull request by colin969**
Checks to add the children of newly added relations.

Example:
Posts 1 and 2 are related.
Post 3 creates a relation with Post 1, a relation with Post 2 is added automatically.

### CODE REVIEW

**Comment by rr-** [comment]
This simplifies the relations feature into something like post pools.
I think it's wise to keep the relation graph directed, for example for stuff such as comics / manga that's of sequential nature.

**Comment by colin969** [comment]
How about a parameter that will include child relations inside the response? (rather than changing the relations of the post itself)

It'd allow for choosing of viewing it as a post pool (which is basically all my content) or ordered content like manga, without changing the relations themselves.

**Comment by rr-** [comment]
Yes, sounds like better choice.

**Comment by sgsunder** [comment]
Stale PR

**Comment by fsnowdin** [comment]
bumping as this would be incredibly useful

**Pull request closed without merging**
